substitutions:
  name: "m5stick"
  devicename: m5stick
  upper_devicename: M5StickC
  friendly_name: "M5Stick C Plus"
  
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  platform: ESP32
  board: m5stick-c
  platformio_options:
    upload_speed: 115200

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "5oN0BK+Sp+qYHr43tDWZs7C1ey+eGxM0paaK+7ACrLE="

ota:
  password: "2a42fb976522bd89531d12b0283c477f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "M5Stick-Plus Fallback Hotspot"
    password: "1I2MESca3Sk0"

captive_portal:

external_components:
  - source: github://martydingo/esphome-axp192
    components: [axp192]

# AXP192 power management - must be present to initialize TFT power on
sensor:
  - platform: axp192
    model: M5STICKC
    address: 0x34
    i2c_id: bus_a
    update_interval: 30s
    battery_level:
      name: "M5Stick Battery Level"
      id: "m5stick_batterylevel"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO37
      inverted: true
    name: ${upper_devicename} Button A
    on_press:
      then:
        - light.turn_on: led1
    on_release:
      then:
        - light.turn_off: led1

  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: ${upper_devicename} Button B
    on_press:
      then:
        - light.turn_on: led1
    on_release:
      then:
        - light.turn_off: led1

light:
  - platform: monochromatic
    output:  builtin_led
    name: ${upper_devicename} Led
    id: led1

output:
  # Buzzer output. to be set to off otherwise the microphone doesn't work.   
  - platform: ledc
    pin:
      number: GPIO2
    id: buzzer
    inverted: false

  - platform: ledc
    pin: 10
    inverted: true
    id: builtin_led

remote_transmitter:
  - pin:
      number: GPIO9
    carrier_duty_percent: 50%
    id: infrared

spi:
  clk_pin: GPIO13
  mosi_pin: GPIO15

i2c:
   - id: bus_a
     sda: GPIO21
     scl: GPIO22
     scan: True

font:
  - file: "gfonts://Roboto"
    id: roboto
    size: 12

color:
  - id: my_red
    red: 100%
    green: 3%
    blue: 5%
  - id: my_black
    red: 100%
    green: 100%
    blue: 100%

# 1.14 inch, 135*240 Colorful TFT LCD, ST7789v2
display:
  - platform:  st7789v
    model: TTGO TDisplay 135x240
    cs_pin: GPIO5
    dc_pin: GPIO23
    reset_pin: GPIO18
    rotation: 270
    lambda: |-
      it.fill(id(my_black));
      it.print(80, 0, id(roboto), id(my_red), TextAlign::TOP_CENTER, "M5Stick Plus v1.1 - Test");

i2s_audio:
  - id: mic_adc
    i2s_lrclk_pin:
       number: GPIO0
       allow_other_uses: true
       ignore_strapping_warning: true
  - id: spk_adc #test for speaker
    i2s_lrclk_pin:
       number: GPIO0
       allow_other_uses: true
       ignore_strapping_warning: true
    i2s_bclk_pin: GPIO26

microphone:
  - platform: i2s_audio
    id: stickc_microphone
    i2s_din_pin: GPIO34
    adc_type: external
    channel: left
    i2s_audio_id: mic_adc
#    bits_per_sample: 16bit #better ??
#    sample_rate: 44100 #better ??
    pdm: true

#media_player:
#  - platform: i2s_audio
#    id: media_out
#    name: ${friendly_name}
#    dac_type: external
#    i2s_lrclk_pin: GPIO21
#    i2s_dout_pin: GPIO25
#    i2s_bclk_pin: GPIO22
#    mode: mono

voice_assistant:
  microphone: stickc_microphone
  on_start:
    - light.turn_on:
        id: led1
        effect: none
  on_tts_start:
    - light.turn_on:
        id: led1
        effect: none
  on_tts_end:
#    - media_player.play_media: !lambda return x;
    - light.turn_on:
        id: led1
        effect: none
  on_end:
    - delay: 1s
#    - wait_until:
#        not:
#          media_player.is_playing: media_out
    - light.turn_on:
        id: led1
        effect: pulse
  on_error:
    - light.turn_on:
        id: led1
        effect: none
    - delay: 1s
    - light.turn_on:
        id: led1
        effect: none
